### ISSUE TITLE
リトライ時に一瞬答えが表示される

### ISSUE THREAD

**Issue by yotsuha0920** [takapiro99/hokkaidle#5]
リトライを行うと、一瞬答えが見えたあとにぼかしが入って見えなくなるため、見えた答えから一発で当てるということが可能になってしまっている。

環境:Android OS 11(Sony SOV41)
　　  最新版のChrome

**Comment by takapiro99** [comment]
@yotsuha0920 コメントあざす！再現方法わからず、今も発生していれば画面キャプチャなどで教えていただいていいですか？

**Comment by yotsuha0920** [comment]
すみません、こちらでも再現できませんでした。
他の方のHokkaidleと混同して送ってしまった可能性があります。申し訳ありません！
